pull_request_rules:
  - name: automatic merge dependabot PRs on CI success and review
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - author=dependabot-preview[bot]
    actions:
      merge:
        method: merge
